### ISSUE TITLE
[Bug] Column 'id' in order clause is ambiguous

### ISSUE THREAD

**Issue by joshmurrayeu** [laravel-json-api/eloquent#12]
I have built up a query within the `Scheme::indexQuery()` and I get the following exception when fetching the entities:

```
PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous
```

This bug occurs when joining with other tables in the `indexQuery()`. The `defaultOrder` method within the `PagePagination` will only use the `primaryKey` in the `orderBy` causing this exception.

**Comment by joshmurrayeu** [comment]
Please see PR: https://github.com/laravel-json-api/eloquent/pull/13

**Comment by lindyhopchris** [comment]
Thanks for reporting and providing the PR. The PR needs to be amended to use the `qualifyColumn()` method Eloquent already provides, but then should be mergable.

**Comment by joshmurrayeu** [comment]
No worries - I've updated the PR as requested. Thanks for a prompt response!

**Comment by lindyhopchris** [comment]
Great thanks, have merged into `develop`.
